version: 2

# This part is necessary otherwise the project is not built
python:
   version: 3.7
   install:
      - requirements: docs/requirements.txt
      - method: pip
        path: .
        
# By default readthedocs does not checkout git submodules
submodules:                                                                                                                          
    include: all
