# Library specified default literals for FlashKit.

[general]

  [general.files]
  checkpoint = '_hdf5_chk_'
  forced     = 'forced'
  grid       = '_hdf5_grd_'
  output     = ''
  plot       = '_hdf5_plt_cnt_'

  [general.mesh]
  iprocs = 1
  jprocs = 1
  kprocs = 1

  [general.paths]
  working = ''

  [general.pipes]
  nofile  = false 
  result  = false

  [general.space]
  ndim = 2
  nxb  = 64
  nyb  = 64
  nzb  = 64
  xrange = [0.0, 1.0]
  yrange = [0.0, 1.0]
  zrange = [0.0, 1.0]

[create]

  [create.block]
  fields = {velx='facex', vely='facey', velz='facez', temp='center'}

  [create.grid]
  xmethod = 'uniform'
  ymethod = 'uniform'
  zmethod = 'uniform'

  [create.xdmf]
  high = 0
  low  = 0
  skip = 1
