# Library specified mappings for default literals in FlashKit.

[create]
  
  [create.grid]
  path = ['general', 'paths', 'working']
  
  [create.init]
  path = ['general', 'paths', 'working']
  
  [create.xdmf]
  grid = ['general', 'files', 'grid']
  path = ['general', 'paths', 'working']
  dest = ['general', 'paths', 'working']
  plot = ['general', 'files', 'plot']
  out  = ['general', 'files', 'output']

