# Library specified mappings for default literals in FlashKit.

[create]
  
  [create.grid]
  iprocs = ['general', 'mesh', 'iprocs']
  jprocs = ['general', 'mesh', 'jprocs']
  kprocs = ['general', 'mesh', 'kprocs']
  ndim   = ['general', 'space', 'ndim']
  nxb    = ['general', 'space', 'nxb']
  nyb    = ['general', 'space', 'nyb']
  nzb    = ['general', 'space', 'nzb']
  dest   = ['general', 'paths', 'working']
  path   = ['general', 'paths', 'working']
  xrange = ['general', 'space', 'xrange']
  yrange = ['general', 'space', 'yrange']
  zrange = ['general', 'space', 'zrange']

  [create.block]
  path = ['general', 'paths', 'working']
  
  [create.xdmf]
  dest = ['general', 'paths', 'working']
  grid = ['general', 'files', 'grid']
  path = ['general', 'paths', 'working']
  plot = ['general', 'files', 'plot']
  out  = ['general', 'files', 'output']

