# Library specified default literals for FlashKit.

[general]

  [general.arch]
  ntasks = 4 

  [general.files]
  checkpoint = '_hdf5_chk_'
  forced     = 'forced'
  grid       = '_hdf5_grd_'
  hosts      = 'hosts'
  output     = ''
  plot       = '_hdf5_plt_cnt_'

  [general.mesh]
  iprocs = 1
  jprocs = 1
  kprocs = 1

  [general.paths]
  jobs    = '~/jobs'
  site     = 'manwe.ddns.net'
  source  = '~/FLASH'
  working = ''

  [general.pipes]
  nofile  = false 
  result  = false

  [general.space]
  grid = 'regular'
  ndim = 2
  nxb  = 64
  nyb  = 64
  nzb  = 64
  xrange = [0.0, 1.0]
  yrange = [0.0, 1.0]
  zrange = [0.0, 1.0]

[analyze]

  [analyze.where]

[build]

  [build.jobs]

    [build.jobs.collection]
    
    [build.jobs.job]

    [build.jobs.simulation]

    [build.jobs.working]

  [build.port]

  [build.scaling]

  [build.simulation]
  jobs     = 1
  optimize = 'opt'
  python   = 2
  subpath  = 'INavierStokes/zoso'

[create]

  [create.batch]
  launch = 'mpirun'
  sources = ['bash', 'run']

  [create.block]
  fields = {velx='facex', vely='facey', velz='facez', temp='center'}

  [create.grid]
  xmethod = 'uniform'
  ymethod = 'uniform'
  zmethod = 'uniform'

  [create.interp]
  fields = {velx='facex', vely='facey', velz='facez', temp='center'}
 
  [create.par]
  sources = ['space', 'mesh']

  [create.tecplot]

  [create.xdmf]
  high = 0
  low  = 0
  skip = 1
