# Library specified mappings for default literals in FlashKit.

[create]
  
  [create.block]
  iprocs = ['general', 'mesh', 'iprocs']
  jprocs = ['general', 'mesh', 'jprocs']
  kprocs = ['general', 'mesh', 'kprocs']
  dest   = ['general', 'paths', 'working']
  path   = ['general', 'paths', 'working']
  nofile = ['general', 'pipes', 'nofile']
  result = ['general', 'pipes', 'result']
  ndim   = ['general', 'space', 'ndim']
  nxb    = ['general', 'space', 'nxb']
  nyb    = ['general', 'space', 'nyb']
  nzb    = ['general', 'space', 'nzb']
  
  [create.grid]
  iprocs = ['general', 'mesh', 'iprocs']
  jprocs = ['general', 'mesh', 'jprocs']
  kprocs = ['general', 'mesh', 'kprocs']
  dest   = ['general', 'paths', 'working']
  path   = ['general', 'paths', 'working']
  nofile = ['general', 'pipes', 'nofile']
  result = ['general', 'pipes', 'result']
  ndim   = ['general', 'space', 'ndim']
  nxb    = ['general', 'space', 'nxb']
  nyb    = ['general', 'space', 'nyb']
  nzb    = ['general', 'space', 'nzb']
  xrange = ['general', 'space', 'xrange']
  yrange = ['general', 'space', 'yrange']
  zrange = ['general', 'space', 'zrange']

  [create.interp]
  grid   = ['general', 'files', 'grid']
  force  = ['general', 'files', 'forced']
  plot   = ['general', 'files', 'plot']
  iprocs = ['general', 'mesh', 'iprocs']
  jprocs = ['general', 'mesh', 'jprocs']
  kprocs = ['general', 'mesh', 'kprocs']
  dest   = ['general', 'paths', 'working']
  path   = ['general', 'paths', 'working']
  nofile = ['general', 'pipes', 'nofile']
  result = ['general', 'pipes', 'result']
  ndim   = ['general', 'space', 'ndim']
  nxb    = ['general', 'space', 'nxb']
  nyb    = ['general', 'space', 'nyb']
  nzb    = ['general', 'space', 'nzb']

  [create.par]
  dest   = ['general', 'paths', 'working']
  nofile = ['general', 'pipes', 'nofile']
  result = ['general', 'pipes', 'result']

  [create.xdmf]
  grid  = ['general', 'files', 'grid']
  force = ['general', 'files', 'forced']
  plot  = ['general', 'files', 'plot']
  out   = ['general', 'files', 'output']
  dest  = ['general', 'paths', 'working']
  path  = ['general', 'paths', 'working']
