# Library specified sources for templating files using FlashKit.

[batch]

  batch.bash.comment = {header = '!/bin/bash', number = -9999}
  
  [batch.slurm]
  job = {value='#SBATCH -J', source=['create', 'batch', 'job'], number=100, _='Job name'}
  nodes = {value='#SBATCH -N', source=['create', 'batch', 'nnodes'], number=200, _='Total # of nodes'}
  tasks = {value='#SBATCH -n', source=['create', 'batch', 'nprocs'], number=300, _='Total # of mpi tasks'}
  
    [batch.slurm.comment]
    header = 'Flashkit Generated SLURM job script'
    number = -5000

  [batch.info]
  module = {value='module list', number=100}
  pwd = {value='pwd', number=200}
  date = {value='date', number=300}

    [batch.info.comment]
    header = 'Information about Job enviornment'
    number = 1000

  [batch.run]
  run = {source=['create', 'batch', 'run'], number=100}

    [batch.run.comment]
    header = 'MPI Job execution Command'
    number = 3000

  [batch.time]
  date = {value='date', number=300}

    [batch.time.comment]
    number = 5000

[parameter]
  
  [parameter.2d]

    [parameter.2d.sinks]
    zmin = ''
    zmax = ''

  [parameter.space]
    
    [parameter.space.comment]
    header = 'Size of computational volume'

    [parameter.space.sources]
    xmin = ['general', 'space', 'xrange', '_0']
    xmax = ['general', 'space', 'xrange', '_1']
    ymin = ['general', 'space', 'yrange', '_0']
    ymax = ['general', 'space', 'yrange', '_1']
    zmin = ['general', 'space', 'zrange', '_0']
    zmax = ['general', 'space', 'zrange', '_1']

  [parameter.mesh]

    [parameter.mesh.comment]
    header = 'Processor Grid (i.e., blocks)'

    [parameter.mesh.sources]
    iProcs = ['general', 'mesh', 'iprocs']
    jProcs = ['general', 'mesh', 'jprocs']
    kProcs = ['general', 'mesh', 'kprocs']

[port]

  [port.hdf5]

    [port.hdf5.steps]

    [port.openmpi.steps]
      
    [port.superlu.steps]
