# Library specified sources for templating files using FlashKit.

[parameter]

  [parameter.space]
    
    [parameter.space.comment]
    header = 'Size of computational volume'

    [parameter.space.sources]
    xmin = ['general', 'space', 'xrange', '_0']
    xmax = ['general', 'space', 'xrange', '_1']
    ymin = ['general', 'space', 'yrange', '_0']
    ymax = ['general', 'space', 'yrange', '_1']
    zmin = ['general', 'space', 'zrange', '_0']
    zmax = ['general', 'space', 'zrange', '_1']

  [parameter.mesh]

    [parameter.mesh.comment]
    header = 'Processor Grid (i.e., blocks)'

    [parameter.mesh.sources]
    iProcs = ['general', 'mesh', 'iprocs']
    jProcs = ['general', 'mesh', 'jprocs']
    kProcs = ['general', 'mesh', 'kprocs']
